name: AgentX
description: "A Personal AI Assistant."
publish_to: 'none'

homepage: https://github.com/IDKSAM27/Agent-X
repository: https://github.com/IDKSAM27/Agent-X

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1 
  firebase_storage: ^13.0.0
  image_picker: ^1.0.7
  image_cropper: ^8.0.0
  google_sign_in: ^6.2.1
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  flutter_dotenv: ^6.0.0
  cloud_firestore: ^6.0.0
  intl: ^0.20.2
  table_calendar: ^3.0.9
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^8.2.0
  injectable: ^2.3.2
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  flutter_animate: ^4.2.0+1
  dio: ^5.3.2
  flutter_riverpod: ^2.4.9 # I may remove this, I already use Bloc for animation
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  flutter_markdown: ^0.6.18
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  connectivity_plus: ^7.0.0
  uuid: ^4.5.2

  # Voice dependencies
  speech_to_text: ^7.3.0
  flutter_tts: ^3.8.3
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  injectable_generator: ^2.4.1
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/*"
